---
- name: Use WSL SSH key
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop: "{{ ssh_items | flatten(levels=1) }}"

- name: Check if emacs repo has already been cloned
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.emacs.d"
  register: "emacs_repo"

- name: Get emacs configuration
  ansible.builtin.git:
    repo: git@github.com:calizarr/.emacs.d.git
    dest: "{{ ansible_env.HOME }}/.emacs.d"
    accept_hostkey: yes
  when: not emacs_repo.stat.exists

- name: Check if dotfiles repo has been cloned
  include_tasks: ./check_dotfiles.yaml

- name: Get dotfiles etc. repo
  ansible.builtin.git:
    repo: git@github.com:calizarr/Misc.git
    dest: "{{ ansible_env.HOME}}/GitHub_Repos/Misc"
    accept_hostkey: yes
  when: not dotfiles_repo.stat.exists

- name: Check if dotfiles repo has been cloned
  include_tasks: ./check_dotfiles.yaml

- name: Get Tmux configuration file and symlink
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/GitHub_Repos/Misc/Config_files/tmux_conf_2.9_and_above"
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    state: link
  when: dotfiles_repo.stat.exists

- name: tmux - get TPM plugin system
  ansible.builtin.git:
    repo: git@github.com:tmux-plugins/tpm.git
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
    accept_hostkey: yes

- name: Set global git config via iteration
  ansible.builtin.git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  loop: "{{ git_config.user | flatten(levels=1) }}"
