- name: Download Chrome deb
  get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: "{{ ansible_env.HOME }}/Downloads/google-chrome-stable_current_amd64.deb"
    mode: '0755'
  register: chrome_deb

- name: Install Chrome
  become: yes
  apt:
    deb: "{{ chrome_deb.dest }}"

- name: Edit chrome scale factor on linux
  become: yes
  lineinfile:
    path: /usr/share/applications/google-chrome.desktop
    regexp: '^Exec=/usr/bin/google-chrome-stable .*%U'
    line: Exec=/usr/bin/google-chrome-stable --force-device-scale-factor=1.5 %U
    state: present
  when: scaling_4k | bool
