---
- name: Reboot Ubuntu VM for post package installation
  become: yes
  shell: "sleep 6 && reboot"
  async: 1
  poll: 0

- name: Wait for the reboot to complete if there was a change
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 180
    timeout: 900
