---
- name: Gnome mouse pointer and text size for 4k screen
  command: "{{ item }}"
  loop:
    # Make mouse pointer larger, default 25
    - gsettings set org.gnome.desktop.interface cursor-size 48
    # Make text larger, default 1.0
    - gsettings set org.gnome.desktop.interface text-scaling-factor 1.3
  when: scaling_4k | bool

- name: Remove Gnome Animations, Screensaver, Session Idling, Change key-theme
  command: "{{ item }}"
  loop:
    # Disable All Animations in Ubuntu
    - gsettings set org.gnome.desktop.interface enable-animations false
    # Disable Idling Session
    - gsettings set org.gnome.desktop.session idle-delay 0
    # Disable Screensaver
    - gsettings set org.gnome.desktop.screensaver lock-enabled false
    # Change to emacs key-theme
    # gsettings set org.gnome.desktop.interface gtk-key-theme "Emacs
    # - gsettings set org.gnome.desktop.interface gtk-key-theme "Default"
