(setq perldoc-obarray (make-vector 1519 nil))
;; Functions
(mapc (lambda (func)
         (set (intern func perldoc-obarray) t))
'(
"*" "-A" "-B" "-C" "-M" "-O" "-R" "-S" "-T" "-W" "-X" "-b" "-c" "-d" "-e"
"-f" "-g" "-k" "-l" "-o" "-p" "-r" "-s" "-t" "-u" "-w" "-x" "-z"
"Otherwise," "Otherwise:" "abs" "accept" "alarm" "atan2" "bind" "binmode"
"bless" "break" "caller" "chdir" "chmod" "chomp" "chop" "chown" "chr"
"chroot" "close" "closedir" "connect" "continue" "cos" "crypt" "dbmclose"
"dbmopen" "default" "defined" "delete" "die" "do" "dump" "each" "endgrent"
"endhostent" "endnetent" "endprotoent" "endpwent" "endservent" "eof" "eval"
"exec" "exists" "exit" "exp" "fcntl" "fileno" "flock" "fork" "format"
"formline" "getc" "getgrent" "getgrgid" "getgrnam" "gethostbyaddr"
"gethostbyname" "gethostent" "getlogin" "getnetbyaddr" "getnetbyname"
"getnetent" "getpeername" "getpgrp" "getppid" "getpriority"
"getprotobyname" "getprotobynumber" "getprotoent" "getpwent" "getpwnam"
"getpwuid" "getservbyname" "getservbyport" "getservent" "getsockname"
"getsockopt" "given" "glob" "gmtime" "goto" "grep" "hex" "import" "index"
"int" "ioctl" "join" "keys" "kill" "last" "lc" "lcfirst" "length" "link"
"listen" "local" "localtime" "lock" "log" "lstat" "m" "map" "mkdir"
"msgctl" "msgget" "msgrcv" "msgsnd" "my" "next" "no" "oct" "open" "opendir"
"ord" "our" "pack" "package" "pipe" "pop" "pos" "print" "printf"
"prototype" "push" "q" "qq" "qr" "quotemeta" "qw" "qx" "rand" "read"
"readdir" "readline" "readlink" "readpipe" "recv" "redo" "ref" "rename"
"require" "reset" "return" "reverse" "rewinddir" "rindex" "rmdir" "s" "say"
"scalar" "seek" "seekdir" "select" "semctl" "semget" "semop" "send"
"setgrent" "sethostent" "setnetent" "setpgrp" "setpriority" "setprotoent"
"setpwent" "setservent" "setsockopt" "shift" "shmctl" "shmget" "shmread"
"shmwrite" "shutdown" "sin" "sleep" "socket" "socketpair" "sort" "splice"
"split" "sprintf" "sqrt" "srand" "stat" "state" "study" "sub" "substr"
"symlink" "syscall" "sysopen" "sysread" "sysseek" "system" "syswrite"
"tell" "telldir" "tie" "tied" "time" "times" "tr" "truncate" "uc" "ucfirst"
"umask" "undef" "unlink" "unpack" "unshift" "untie" "use" "utime" "values"
"vec" "wait" "waitpid" "wantarray" "warn" "when" "write" "y"))

;; Modules
(mapc (lambda (mod)
         (intern mod perldoc-obarray))
'(
"AnyDBM_File" "App::Cpan" "App::Prove" "App::Prove::State"
"App::Prove::State::Result" "App::Prove::State::Result::Test"
"Archive::Extract" "Archive::Tar" "Archive::Tar::Constant"
"Archive::Tar::File" "Attribute::Handlers" "AutoLoader" "AutoSplit" "B"
"B::Concise" "B::Debug" "B::Deparse" "B::Lint" "B::Lint::Debug"
"B::Showlex" "B::Terse" "B::Xref" "Benchmark" "CGI" "CGI::Apache"
"CGI::Carp" "CGI::Cookie" "CGI::Fast" "CGI::Pretty" "CGI::Push"
"CGI::Switch" "CGI::Util" "CORE" "CPAN" "CPAN::API::HOWTO" "CPAN::Author"
"CPAN::Bundle" "CPAN::CacheMgr" "CPAN::Complete" "CPAN::Debug"
"CPAN::DeferredCode" "CPAN::Distribution" "CPAN::Distroprefs"
"CPAN::Distrostatus" "CPAN::Exception::RecursiveDependency"
"CPAN::Exception::blocked_urllist" "CPAN::Exception::yaml_not_installed"
"CPAN::FTP" "CPAN::FTP::netrc" "CPAN::FirstTime" "CPAN::HTTP::Client"
"CPAN::HTTP::Credentials" "CPAN::HandleConfig" "CPAN::Index"
"CPAN::InfoObj" "CPAN::Kwalify" "CPAN::LWP::UserAgent" "CPAN::Meta"
"CPAN::Meta::Converter" "CPAN::Meta::Feature" "CPAN::Meta::History"
"CPAN::Meta::Prereqs" "CPAN::Meta::Spec" "CPAN::Meta::Validator"
"CPAN::Meta::YAML" "CPAN::Mirrors" "CPAN::Module" "CPAN::Nox"
"CPAN::Prompt" "CPAN::Queue" "CPAN::Shell" "CPAN::Tarzip" "CPAN::URL"
"CPAN::Version" "CPANPLUS" "CPANPLUS::Backend" "CPANPLUS::Backend::RV"
"CPANPLUS::Config" "CPANPLUS::Configure" "CPANPLUS::Configure::Setup"
"CPANPLUS::Dist" "CPANPLUS::Dist::Autobundle" "CPANPLUS::Dist::Base"
"CPANPLUS::Dist::Build" "CPANPLUS::Dist::Build::Constants"
"CPANPLUS::Dist::MM" "CPANPLUS::Dist::Sample" "CPANPLUS::Error"
"CPANPLUS::FAQ" "CPANPLUS::Hacking" "CPANPLUS::Internals"
"CPANPLUS::Internals::Constants" "CPANPLUS::Internals::Constants::Report"
"CPANPLUS::Internals::Extract" "CPANPLUS::Internals::Fetch"
"CPANPLUS::Internals::Report" "CPANPLUS::Internals::Search"
"CPANPLUS::Internals::Source" "CPANPLUS::Internals::Source::Memory"
"CPANPLUS::Internals::Source::SQLite"
"CPANPLUS::Internals::Source::SQLite::Tie" "CPANPLUS::Internals::Utils"
"CPANPLUS::Internals::Utils::Autoflush" "CPANPLUS::Module"
"CPANPLUS::Module::Author" "CPANPLUS::Module::Author::Fake"
"CPANPLUS::Module::Checksums" "CPANPLUS::Module::Fake"
"CPANPLUS::Module::Signature" "CPANPLUS::Selfupdate" "CPANPLUS::Shell"
"CPANPLUS::Shell::Classic" "CPANPLUS::Shell::Default"
"CPANPLUS::Shell::Default::Plugins::CustomSource"
"CPANPLUS::Shell::Default::Plugins::HOWTO"
"CPANPLUS::Shell::Default::Plugins::Remote"
"CPANPLUS::Shell::Default::Plugins::Source" "Carp" "Carp::Heavy"
"Class::Struct" "Compress::Raw::Bzip2" "Compress::Raw::Zlib"
"Compress::Zlib" "Config" "Config::Extensions" "Cwd" "DB" "DBM_Filter"
"DBM_Filter::compress" "DBM_Filter::encode" "DBM_Filter::int32"
"DBM_Filter::null" "DBM_Filter::utf8" "DB_File" "Data::Dumper"
"Devel::DProf" "Devel::InnerPackage" "Devel::PPPort" "Devel::Peek"
"Devel::SelfStubber" "Digest" "Digest::MD5" "Digest::SHA" "Digest::base"
"Digest::file" "DirHandle" "Dumpvalue" "DynaLoader" "Encode"
"Encode::Alias" "Encode::Byte" "Encode::CJKConstants" "Encode::CN"
"Encode::CN::HZ" "Encode::Config" "Encode::EBCDIC" "Encode::Encoder"
"Encode::Encoding" "Encode::GSM0338" "Encode::Guess" "Encode::JP"
"Encode::JP::H2Z" "Encode::JP::JIS7" "Encode::KR" "Encode::KR::2022_KR"
"Encode::MIME::Header" "Encode::MIME::Header::ISO_2022_JP"
"Encode::MIME::Name" "Encode::PerlIO" "Encode::Supported" "Encode::Symbol"
"Encode::TW" "Encode::Unicode" "Encode::Unicode::UTF7" "English" "Env"
"Errno" "Exporter" "Exporter::Heavy" "ExtUtils::CBuilder"
"ExtUtils::CBuilder::Base" "ExtUtils::CBuilder::Platform::Unix"
"ExtUtils::CBuilder::Platform::VMS" "ExtUtils::CBuilder::Platform::Windows"
"ExtUtils::CBuilder::Platform::Windows::BCC"
"ExtUtils::CBuilder::Platform::Windows::GCC"
"ExtUtils::CBuilder::Platform::Windows::MSVC"
"ExtUtils::CBuilder::Platform::aix" "ExtUtils::CBuilder::Platform::cygwin"
"ExtUtils::CBuilder::Platform::darwin"
"ExtUtils::CBuilder::Platform::dec_osf" "ExtUtils::CBuilder::Platform::os2"
"ExtUtils::Command" "ExtUtils::Command::MM" "ExtUtils::Constant"
"ExtUtils::Constant::Base" "ExtUtils::Constant::ProxySubs"
"ExtUtils::Constant::Utils" "ExtUtils::Constant::XS" "ExtUtils::Embed"
"ExtUtils::Install" "ExtUtils::Installed" "ExtUtils::Liblist"
"ExtUtils::Liblist::Kid" "ExtUtils::MM" "ExtUtils::MM_AIX"
"ExtUtils::MM_Any" "ExtUtils::MM_BeOS" "ExtUtils::MM_Cygwin"
"ExtUtils::MM_DOS" "ExtUtils::MM_Darwin" "ExtUtils::MM_MacOS"
"ExtUtils::MM_NW5" "ExtUtils::MM_OS2" "ExtUtils::MM_QNX"
"ExtUtils::MM_UWIN" "ExtUtils::MM_Unix" "ExtUtils::MM_VMS"
"ExtUtils::MM_VOS" "ExtUtils::MM_Win32" "ExtUtils::MM_Win95" "ExtUtils::MY"
"ExtUtils::MakeMaker" "ExtUtils::MakeMaker::Config"
"ExtUtils::MakeMaker::FAQ" "ExtUtils::MakeMaker::Tutorial"
"ExtUtils::MakeMaker::YAML" "ExtUtils::Manifest" "ExtUtils::Miniperl"
"ExtUtils::Mkbootstrap" "ExtUtils::Mksymlists" "ExtUtils::Packlist"
"ExtUtils::ParseXS" "ExtUtils::testlib" "Fatal" "Fcntl" "File::Basename"
"File::CheckTree" "File::Compare" "File::Copy" "File::DosGlob"
"File::Fetch" "File::Find" "File::Glob" "File::GlobMapper" "File::Path"
"File::Spec" "File::Spec::Cygwin" "File::Spec::Epoc"
"File::Spec::Functions" "File::Spec::Mac" "File::Spec::OS2"
"File::Spec::Unix" "File::Spec::VMS" "File::Spec::Win32" "File::Temp"
"File::stat" "FileCache" "FileHandle" "Filter::Simple" "Filter::Util::Call"
"FindBin" "GDBM_File" "Getopt::Long" "Getopt::Std" "HTTP::Tiny"
"Hash::Util" "Hash::Util::FieldHash" "I18N::Collate" "I18N::LangTags"
"I18N::LangTags::Detect" "I18N::LangTags::List" "I18N::Langinfo" "IO"
"IO::Compress::Adapter::Bzip2" "IO::Compress::Adapter::Deflate"
"IO::Compress::Adapter::Identity" "IO::Compress::Base"
"IO::Compress::Base::Common" "IO::Compress::Bzip2" "IO::Compress::Deflate"
"IO::Compress::Gzip" "IO::Compress::Gzip::Constants"
"IO::Compress::RawDeflate" "IO::Compress::Zip"
"IO::Compress::Zip::Constants" "IO::Compress::Zlib::Constants"
"IO::Compress::Zlib::Extra" "IO::Dir" "IO::File" "IO::Handle" "IO::Pipe"
"IO::Poll" "IO::Seekable" "IO::Select" "IO::Socket" "IO::Socket::INET"
"IO::Socket::UNIX" "IO::Uncompress::Adapter::Bunzip2"
"IO::Uncompress::Adapter::Identity" "IO::Uncompress::Adapter::Inflate"
"IO::Uncompress::AnyInflate" "IO::Uncompress::AnyUncompress"
"IO::Uncompress::Base" "IO::Uncompress::Bunzip2" "IO::Uncompress::Gunzip"
"IO::Uncompress::Inflate" "IO::Uncompress::RawInflate"
"IO::Uncompress::Unzip" "IO::Zlib" "IPC::Cmd" "IPC::Msg" "IPC::Open2"
"IPC::Open3" "IPC::Semaphore" "IPC::SharedMem" "IPC::SysV" "JSON::PP"
"JSON::PP::Boolean" "List::Util" "List::Util::PP" "List::Util::XS"
"Locale::Codes" "Locale::Codes::Changes" "Locale::Codes::Country"
"Locale::Codes::Currency" "Locale::Codes::Language" "Locale::Codes::Script"
"Locale::Constants" "Locale::Country" "Locale::Currency" "Locale::Language"
"Locale::Maketext" "Locale::Maketext::Cookbook" "Locale::Maketext::Guts"
"Locale::Maketext::GutsLoader" "Locale::Maketext::Simple"
"Locale::Maketext::TPJ13" "Locale::Script" "Log::Message"
"Log::Message::Config" "Log::Message::Handlers" "Log::Message::Item"
"Log::Message::Simple" "MIME::Base64" "MIME::QuotedPrint" "Math::BigFloat"
"Math::BigFloat::Trace" "Math::BigInt" "Math::BigInt::Calc"
"Math::BigInt::CalcEmu" "Math::BigInt::FastCalc" "Math::BigInt::Trace"
"Math::BigRat" "Math::Complex" "Math::Trig" "Memoize"
"Memoize::AnyDBM_File" "Memoize::Expire" "Memoize::ExpireFile"
"Memoize::ExpireTest" "Memoize::NDBM_File" "Memoize::SDBM_File"
"Memoize::Storable" "Module::Build" "Module::Build::API"
"Module::Build::Authoring" "Module::Build::Base" "Module::Build::Bundling"
"Module::Build::Compat" "Module::Build::Config" "Module::Build::ConfigData"
"Module::Build::Cookbook" "Module::Build::Dumper"
"Module::Build::ModuleInfo" "Module::Build::Notes"
"Module::Build::PPMMaker" "Module::Build::Platform::Amiga"
"Module::Build::Platform::Default" "Module::Build::Platform::EBCDIC"
"Module::Build::Platform::MPEiX" "Module::Build::Platform::MacOS"
"Module::Build::Platform::RiscOS" "Module::Build::Platform::Unix"
"Module::Build::Platform::VMS" "Module::Build::Platform::VOS"
"Module::Build::Platform::Windows" "Module::Build::Platform::aix"
"Module::Build::Platform::cygwin" "Module::Build::Platform::darwin"
"Module::Build::Platform::os2" "Module::Build::PodParser"
"Module::Build::Version" "Module::Build::YAML" "Module::CoreList"
"Module::Load" "Module::Load::Conditional" "Module::Loaded"
"Module::Metadata" "Module::Pluggable" "Module::Pluggable::Object"
"NDBM_File" "NEXT" "Net::Cmd" "Net::Config" "Net::Domain" "Net::FTP"
"Net::FTP::A" "Net::FTP::E" "Net::FTP::I" "Net::FTP::L"
"Net::FTP::dataconn" "Net::NNTP" "Net::Netrc" "Net::POP3" "Net::Ping"
"Net::SMTP" "Net::Time" "Net::hostent" "Net::libnetFAQ" "Net::netent"
"Net::protoent" "Net::servent" "O" "ODBM_File" "Object::Accessor" "Opcode"
"POSIX" "Package::Constants" "Params::Check" "Parse::CPAN::Meta"
"Perl::OSType" "PerlIO" "PerlIO::encoding" "PerlIO::scalar" "PerlIO::via"
"PerlIO::via::QuotedPrint" "Pod::Checker" "Pod::Escapes" "Pod::Find"
"Pod::Functions" "Pod::Html" "Pod::InputObjects" "Pod::LaTeX" "Pod::Man"
"Pod::ParseLink" "Pod::ParseUtils" "Pod::Parser" "Pod::Perldoc"
"Pod::Perldoc::BaseTo" "Pod::Perldoc::GetOptsOO" "Pod::Perldoc::ToChecker"
"Pod::Perldoc::ToMan" "Pod::Perldoc::ToNroff" "Pod::Perldoc::ToPod"
"Pod::Perldoc::ToRtf" "Pod::Perldoc::ToText" "Pod::Perldoc::ToTk"
"Pod::Perldoc::ToXml" "Pod::PlainText" "Pod::Select" "Pod::Simple"
"Pod::Simple::BlackBox" "Pod::Simple::Checker" "Pod::Simple::Debug"
"Pod::Simple::DumpAsText" "Pod::Simple::DumpAsXML" "Pod::Simple::HTML"
"Pod::Simple::HTMLBatch" "Pod::Simple::HTMLLegacy"
"Pod::Simple::LinkSection" "Pod::Simple::Methody" "Pod::Simple::Progress"
"Pod::Simple::PullParser" "Pod::Simple::PullParserEndToken"
"Pod::Simple::PullParserStartToken" "Pod::Simple::PullParserTextToken"
"Pod::Simple::PullParserToken" "Pod::Simple::RTF" "Pod::Simple::Search"
"Pod::Simple::SimpleTree" "Pod::Simple::Subclassing" "Pod::Simple::Text"
"Pod::Simple::TextContent" "Pod::Simple::TiedOutFH"
"Pod::Simple::Transcode" "Pod::Simple::TranscodeDumb"
"Pod::Simple::TranscodeSmart" "Pod::Simple::XHTML"
"Pod::Simple::XMLOutStream" "Pod::Text" "Pod::Text::Color"
"Pod::Text::Overstrike" "Pod::Text::Termcap" "Pod::Usage" "SDBM_File"
"Safe" "Scalar::Util" "Scalar::Util::PP" "Search::Dict" "SelectSaver"
"SelfLoader" "Shell" "Socket" "Storable" "Symbol" "Sys::Hostname"
"Sys::Syslog" "TAP::Base" "TAP::Formatter::Base" "TAP::Formatter::Color"
"TAP::Formatter::Console" "TAP::Formatter::Console::ParallelSession"
"TAP::Formatter::Console::Session" "TAP::Formatter::File"
"TAP::Formatter::File::Session" "TAP::Formatter::Session" "TAP::Harness"
"TAP::Harness::Beyond" "TAP::Object" "TAP::Parser"
"TAP::Parser::Aggregator" "TAP::Parser::Grammar" "TAP::Parser::Iterator"
"TAP::Parser::Iterator::Array" "TAP::Parser::Iterator::Process"
"TAP::Parser::Iterator::Stream" "TAP::Parser::IteratorFactory"
"TAP::Parser::Multiplexer" "TAP::Parser::Result"
"TAP::Parser::Result::Bailout" "TAP::Parser::Result::Comment"
"TAP::Parser::Result::Plan" "TAP::Parser::Result::Pragma"
"TAP::Parser::Result::Test" "TAP::Parser::Result::Unknown"
"TAP::Parser::Result::Version" "TAP::Parser::Result::YAML"
"TAP::Parser::ResultFactory" "TAP::Parser::Scheduler"
"TAP::Parser::Scheduler::Job" "TAP::Parser::Scheduler::Spinner"
"TAP::Parser::Source" "TAP::Parser::SourceHandler"
"TAP::Parser::SourceHandler::Executable" "TAP::Parser::SourceHandler::File"
"TAP::Parser::SourceHandler::Handle" "TAP::Parser::SourceHandler::Perl"
"TAP::Parser::SourceHandler::RawTAP" "TAP::Parser::Utils"
"TAP::Parser::YAMLish::Reader" "TAP::Parser::YAMLish::Writer"
"Term::ANSIColor" "Term::Cap" "Term::Complete" "Term::ReadLine" "Term::UI"
"Term::UI::History" "Test" "Test::Builder" "Test::Builder::Module"
"Test::Builder::Tester" "Test::Builder::Tester::Color" "Test::Harness"
"Test::More" "Test::Simple" "Test::Tutorial" "Text::Abbrev"
"Text::Balanced" "Text::ParseWords" "Text::Soundex" "Text::Tabs"
"Text::Wrap" "Thread" "Thread::Queue" "Thread::Semaphore" "Tie::Array"
"Tie::File" "Tie::Handle" "Tie::Hash" "Tie::Hash::NamedCapture"
"Tie::Memoize" "Tie::RefHash" "Tie::Scalar" "Tie::StdHandle"
"Tie::SubstrHash" "Time::HiRes" "Time::Local" "Time::Piece" "Time::Seconds"
"Time::gmtime" "Time::localtime" "Time::tm" "UNIVERSAL" "Unicode::Collate"
"Unicode::Collate::CJK::Big5" "Unicode::Collate::CJK::GB2312"
"Unicode::Collate::CJK::JISX0208" "Unicode::Collate::CJK::Korean"
"Unicode::Collate::CJK::Pinyin" "Unicode::Collate::CJK::Stroke"
"Unicode::Collate::Locale" "Unicode::Normalize" "Unicode::UCD"
"User::grent" "User::pwent" "Version::Internals" "Version::Requirements"
"Win32" "Win32API::File" "Win32CORE" "XSLoader" "attributes" "autodie"
"autodie::exception" "autodie::exception::system" "autodie::hints"
"autouse" "base" "bigint" "bignum" "bigrat" "blib" "bytes" "charnames"
"constant" "deprecate" "diagnostics" "encoding" "encoding::warnings"
"feature" "fields" "filetest" "if" "inc::latest" "inc::latest::private"
"integer" "less" "lib" "locale" "mro" "open.pod" "ops" "overload"
"overload::numbers" "overloading" "parent" "pods::a2p" "pods::perl"
"pods::perl5004delta" "pods::perl5005delta" "pods::perl5100delta"
"pods::perl5101delta" "pods::perl5110delta" "pods::perl5111delta"
"pods::perl5112delta" "pods::perl5113delta" "pods::perl5114delta"
"pods::perl5115delta" "pods::perl5120delta" "pods::perl5121delta"
"pods::perl5122delta" "pods::perl5123delta" "pods::perl5130delta"
"pods::perl51310delta" "pods::perl51311delta" "pods::perl5131delta"
"pods::perl5132delta" "pods::perl5133delta" "pods::perl5134delta"
"pods::perl5135delta" "pods::perl5136delta" "pods::perl5137delta"
"pods::perl5138delta" "pods::perl5139delta" "pods::perl5140delta"
"pods::perl5141delta" "pods::perl5142delta" "pods::perl5143delta"
"pods::perl5144delta" "pods::perl561delta" "pods::perl56delta"
"pods::perl570delta" "pods::perl571delta" "pods::perl572delta"
"pods::perl573delta" "pods::perl581delta" "pods::perl582delta"
"pods::perl583delta" "pods::perl584delta" "pods::perl585delta"
"pods::perl586delta" "pods::perl587delta" "pods::perl588delta"
"pods::perl589delta" "pods::perl58delta" "pods::perl590delta"
"pods::perl591delta" "pods::perl592delta" "pods::perl593delta"
"pods::perl594delta" "pods::perl595delta" "pods::perlaix" "pods::perlamiga"
"pods::perlapi" "pods::perlapio" "pods::perlartistic" "pods::perlbeos"
"pods::perlbook" "pods::perlboot" "pods::perlbot" "pods::perlbs2000"
"pods::perlcall" "pods::perlce" "pods::perlcheat" "pods::perlclib"
"pods::perlcn" "pods::perlcommunity" "pods::perlcompile" "pods::perlcygwin"
"pods::perldata" "pods::perldbmfilter" "pods::perldebguts"
"pods::perldebtut" "pods::perldebug" "pods::perldelta" "pods::perldgux"
"pods::perldiag" "pods::perldoc" "pods::perldos" "pods::perldsc"
"pods::perlebcdic" "pods::perlembed" "pods::perlepoc" "pods::perlfaq"
"pods::perlfaq1" "pods::perlfaq2" "pods::perlfaq3" "pods::perlfaq4"
"pods::perlfaq5" "pods::perlfaq6" "pods::perlfaq7" "pods::perlfaq8"
"pods::perlfaq9" "pods::perlfilter" "pods::perlfork" "pods::perlform"
"pods::perlfreebsd" "pods::perlfunc" "pods::perlgit" "pods::perlglossary"
"pods::perlgpl" "pods::perlguts" "pods::perlhack" "pods::perlhacktips"
"pods::perlhacktut" "pods::perlhaiku" "pods::perlhist" "pods::perlhpux"
"pods::perlhurd" "pods::perlintern" "pods::perlinterp" "pods::perlintro"
"pods::perliol" "pods::perlipc" "pods::perlirix" "pods::perljp"
"pods::perlko" "pods::perllexwarn" "pods::perllinux" "pods::perllocale"
"pods::perllol" "pods::perlmacos" "pods::perlmacosx" "pods::perlmod"
"pods::perlmodinstall" "pods::perlmodlib" "pods::perlmodstyle"
"pods::perlmpeix" "pods::perlmroapi" "pods::perlnetware" "pods::perlnewmod"
"pods::perlnumber" "pods::perlobj" "pods::perlop" "pods::perlopenbsd"
"pods::perlopentut" "pods::perlos2" "pods::perlos390" "pods::perlos400"
"pods::perlpacktut" "pods::perlperf" "pods::perlplan9" "pods::perlpod"
"pods::perlpodspec" "pods::perlpodstyle" "pods::perlpolicy"
"pods::perlport" "pods::perlpragma" "pods::perlqnx" "pods::perlre"
"pods::perlreapi" "pods::perlrebackslash" "pods::perlrecharclass"
"pods::perlref" "pods::perlreftut" "pods::perlreguts" "pods::perlrequick"
"pods::perlreref" "pods::perlretut" "pods::perlriscos" "pods::perlrun"
"pods::perlsec" "pods::perlsolaris" "pods::perlsource" "pods::perlstyle"
"pods::perlsub" "pods::perlsymbian" "pods::perlsyn" "pods::perlthrtut"
"pods::perltie" "pods::perltoc" "pods::perltodo" "pods::perltooc"
"pods::perltoot" "pods::perltrap" "pods::perltru64" "pods::perltw"
"pods::perlunicode" "pods::perlunifaq" "pods::perluniintro"
"pods::perluniprops" "pods::perlunitut" "pods::perlutil" "pods::perluts"
"pods::perlvar" "pods::perlvmesa" "pods::perlvms" "pods::perlvos"
"pods::perlwin32" "pods::perlxs" "pods::perlxstut" "re" "sigtrap"
"sort.pod" "strict" "subs" "threads" "threads::shared" "utf8" "vars"
"version" "vmsish" "warnings" "warnings::register"
"x86_64-cygwin-threads::B" "x86_64-cygwin-threads::B::Concise"
"x86_64-cygwin-threads::B::Showlex" "x86_64-cygwin-threads::B::Terse"
"x86_64-cygwin-threads::B::Xref"
"x86_64-cygwin-threads::Compress::Raw::Bzip2"
"x86_64-cygwin-threads::Compress::Raw::Zlib"
"x86_64-cygwin-threads::Config" "x86_64-cygwin-threads::Cwd"
"x86_64-cygwin-threads::DB_File" "x86_64-cygwin-threads::Data::Dumper"
"x86_64-cygwin-threads::Devel::DProf"
"x86_64-cygwin-threads::Devel::PPPort" "x86_64-cygwin-threads::Devel::Peek"
"x86_64-cygwin-threads::Digest::MD5" "x86_64-cygwin-threads::Digest::SHA"
"x86_64-cygwin-threads::DynaLoader" "x86_64-cygwin-threads::Encode"
"x86_64-cygwin-threads::Encode::Alias"
"x86_64-cygwin-threads::Encode::Byte"
"x86_64-cygwin-threads::Encode::CJKConstants"
"x86_64-cygwin-threads::Encode::CN" "x86_64-cygwin-threads::Encode::CN::HZ"
"x86_64-cygwin-threads::Encode::Config"
"x86_64-cygwin-threads::Encode::EBCDIC"
"x86_64-cygwin-threads::Encode::Encoder"
"x86_64-cygwin-threads::Encode::Encoding"
"x86_64-cygwin-threads::Encode::GSM0338"
"x86_64-cygwin-threads::Encode::Guess" "x86_64-cygwin-threads::Encode::JP"
"x86_64-cygwin-threads::Encode::JP::H2Z"
"x86_64-cygwin-threads::Encode::JP::JIS7"
"x86_64-cygwin-threads::Encode::KR"
"x86_64-cygwin-threads::Encode::KR::2022_KR"
"x86_64-cygwin-threads::Encode::MIME::Header"
"x86_64-cygwin-threads::Encode::MIME::Header::ISO_2022_JP"
"x86_64-cygwin-threads::Encode::MIME::Name"
"x86_64-cygwin-threads::Encode::Symbol" "x86_64-cygwin-threads::Encode::TW"
"x86_64-cygwin-threads::Encode::Unicode"
"x86_64-cygwin-threads::Encode::Unicode::UTF7"
"x86_64-cygwin-threads::Errno" "x86_64-cygwin-threads::Fcntl"
"x86_64-cygwin-threads::File::Glob" "x86_64-cygwin-threads::File::Spec"
"x86_64-cygwin-threads::File::Spec::Cygwin"
"x86_64-cygwin-threads::File::Spec::Epoc"
"x86_64-cygwin-threads::File::Spec::Functions"
"x86_64-cygwin-threads::File::Spec::Mac"
"x86_64-cygwin-threads::File::Spec::OS2"
"x86_64-cygwin-threads::File::Spec::Unix"
"x86_64-cygwin-threads::File::Spec::VMS"
"x86_64-cygwin-threads::File::Spec::Win32"
"x86_64-cygwin-threads::Filter::Util::Call"
"x86_64-cygwin-threads::GDBM_File" "x86_64-cygwin-threads::Hash::Util"
"x86_64-cygwin-threads::Hash::Util::FieldHash"
"x86_64-cygwin-threads::I18N::Langinfo" "x86_64-cygwin-threads::IO"
"x86_64-cygwin-threads::IO::Dir" "x86_64-cygwin-threads::IO::File"
"x86_64-cygwin-threads::IO::Handle" "x86_64-cygwin-threads::IO::Pipe"
"x86_64-cygwin-threads::IO::Poll" "x86_64-cygwin-threads::IO::Seekable"
"x86_64-cygwin-threads::IO::Select" "x86_64-cygwin-threads::IO::Socket"
"x86_64-cygwin-threads::IO::Socket::INET"
"x86_64-cygwin-threads::IO::Socket::UNIX" "x86_64-cygwin-threads::IPC::Msg"
"x86_64-cygwin-threads::IPC::Semaphore"
"x86_64-cygwin-threads::IPC::SharedMem" "x86_64-cygwin-threads::IPC::SysV"
"x86_64-cygwin-threads::List::Util" "x86_64-cygwin-threads::List::Util::PP"
"x86_64-cygwin-threads::List::Util::XS"
"x86_64-cygwin-threads::MIME::Base64"
"x86_64-cygwin-threads::MIME::QuotedPrint"
"x86_64-cygwin-threads::Math::BigInt::FastCalc"
"x86_64-cygwin-threads::NDBM_File" "x86_64-cygwin-threads::O"
"x86_64-cygwin-threads::ODBM_File" "x86_64-cygwin-threads::Opcode"
"x86_64-cygwin-threads::POSIX" "x86_64-cygwin-threads::PerlIO::encoding"
"x86_64-cygwin-threads::PerlIO::scalar"
"x86_64-cygwin-threads::PerlIO::via" "x86_64-cygwin-threads::SDBM_File"
"x86_64-cygwin-threads::Scalar::Util"
"x86_64-cygwin-threads::Scalar::Util::PP" "x86_64-cygwin-threads::Socket"
"x86_64-cygwin-threads::Storable" "x86_64-cygwin-threads::Sys::Hostname"
"x86_64-cygwin-threads::Sys::Syslog" "x86_64-cygwin-threads::Text::Soundex"
"x86_64-cygwin-threads::Tie::Hash::NamedCapture"
"x86_64-cygwin-threads::Time::HiRes" "x86_64-cygwin-threads::Time::Piece"
"x86_64-cygwin-threads::Time::Seconds"
"x86_64-cygwin-threads::Unicode::Collate"
"x86_64-cygwin-threads::Unicode::Collate::Locale"
"x86_64-cygwin-threads::Unicode::Normalize" "x86_64-cygwin-threads::Win32"
"x86_64-cygwin-threads::Win32API::File" "x86_64-cygwin-threads::Win32CORE"
"x86_64-cygwin-threads::attributes" "x86_64-cygwin-threads::encoding"
"x86_64-cygwin-threads::lib" "x86_64-cygwin-threads::mro"
"x86_64-cygwin-threads::ops" "x86_64-cygwin-threads::re"
"x86_64-cygwin-threads::threads" "x86_64-cygwin-threads::threads::shared"))
