---
- name: Install the latest python version
  command: "pyenv install -s {{ python_settings.latest }}"

- name: Set the latest python version as global
  command: "pyenv global {{ python_settings.latest }}"

- name: Check if pyenv initialization has been added to .profile
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.profile"
    block: "{{ python_settings.pyenv_init }}"
    state: present

- name: Check if pyenv initialization has been added to .bashrc
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    block: "{{ python_settings.pyenv_init }}"
    state: present
