---
- name: Check if Linuxbrew is installed
  include_tasks: check_linuxbrew.yaml

- name: Fail if Linuxbrew is not installed and install_linuxbrew_if_missing is False
  ansible.builtin.fail:
    msg: "Linuxbrew is missing...Install it"
  when: >-
    not linuxbrew_check.stat.exists | bool and
    not install_linuxbrew_if_missing | bool

- name: Create /home/linuxbrew
  become: yes
  ansible.builtin.file:
    path: "{{ linuxbrew_path }}"
    state: directory
    mode: u=rwx,g=rwx,o=rwx
  when: not linuxbrew_check.stat.exists | bool

- name: Installing Linuxbrew
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  environment:
    CI: 1
  when: >-
    not linuxbrew_check.stat.exists | bool and
    install_linuxbrew_if_missing | bool

- name: Add Linuxbrew to .profile and .bashrc
  ansible.builtin.lineinfile:
    line: "eval $({{ linuxbrew_path }}/.linuxbrew/bin/brew shellenv)"
    insertafter: EOF
    path: "{{ item }}"
    state: present
  loop:
    - "{{ ansible_env.HOME }}/.profile"
    - "{{ ansible_env.HOME }}/.bashrc"

- name: Check if Linuxbrew is installed
  include_tasks: check_linuxbrew.yaml

- name: Show results of checking linuxbrew installation
  ansible.builtin.debug:
    var: linuxbrew_check.stat.exists
    verbosity: 1

- name: Updating Linuxbrew
  ansible.builtin.homebrew:
    update_homebrew: yes
    path: "{{ linuxbrew_path }}/.linuxbrew/bin/"
  when: linuxbrew_check.stat.exists | bool

- name: Installing Linuxbrew packages
  ansible.builtin.homebrew:
    name: "{{ brew_packages }}"
    state: present
    path: "{{ linuxbrew_path }}/.linuxbrew/bin/"
    upgrade_all: "{{ upgrade_linuxbrew_packages }}"
  when: linuxbrew_check.stat.exists | bool
