---
apt_keys:
  - https://apt.releases.hashicorp.com/gpg
  - https://download.docker.com/linux/ubuntu/gpg

apt_repos:
  - 'ppa:alexlarsson/flatpak'
  - 'ppa:ubuntu-elisp/ppa'
  - "deb [arch=amd64] https://apt.releases.hashicorp.com {{ lsb_release.stdout }} main"
  - "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable"

apt_packages:
  - 'apt-transport-https'
  - 'build-essential'
  - 'ca-certificates'
  - 'containerd.io'
  - 'curl'
  - 'docker-ce'
  - 'docker-ce-cli'
  - 'emacs-snapshot'
  - 'flatpak'
  - 'fonts-powerline'
  - 'git'
  - 'gnupg-agent'
  - 'libappindicator1'
  - 'libbz2-dev'
  - 'libffi-dev'
  - 'libindicator7'
  - 'liblzma-dev'
  - 'libncurses5-dev'
  - 'libncursesw5-dev'
  - 'libreadline-dev'
  - 'libsdl2-2.0-0'
  - 'libsdl2-dev'
  - 'libsqlite3-dev'
  - 'libssl-dev'
  - 'libxss1'
  - 'llvm'
  - 'openjdk-11-jdk'
  - 'python-openssl'
  - 'python3-pip' # Needed for terminator themes
  - 'qt5-default'
  - 'software-properties-common'
  - 'terminator'
  - 'terraform'
  - 'tk-dev'
  - 'vault'
  - 'wget'
  - 'x11-utils' # Mouse binding for back/forward keys
  - 'xautomation' # Mouse binding for back/forward keys
  - 'xclip'
  - 'xz-utils'
  - 'zlib1g-dev'
  - 'zsh'

system_pip_packages:
  - 'requests' # Needed for terminator themes

snap_packages:
  - 'keepassxc'
  - 'htop'
snap_classic_packages:
  - 'slack'
