---
- hosts: nanaya_vm
  remote_user: calizarr
  tasks:
  - name: Add emacs apt repository
    become: yes
    apt_repository:
      repo: ppa:ansible/ansible
  - name: Apt update and upgrade
    become: yes
    apt:
      upgrade: dist
      update_cache: yes
  - name: Install Emacs
    become: yes
    apt:
      name: emacs-snapshot
      state: present
  - name: Install ZSH
    become: yes
    
    
  
