---
- hosts: nanaya_vm
  remote_user: calizarr
  vars:
    brew_packages:
      - 'docker'
      - 'docker-compose'
      - 'git'
      - 'hub'
      - 'jq'
      - 'pyenv'
      - 'tmux'
      - 'zsh'
      - 'zsh-autosuggestions'
      - 'zsh-completions'
      - 'zsh-history-substring-search'
      - 'zsh-syntax-highlighting'
    brew_cask_packages:
      - 'docker'
    snap_packages:
      - 'keepassxc'
    snap_classic_packages:
      - 'slack'
    install_linuxbrew_if_missing: true
    upgrade_homebrew_packages: false

  tasks:

  - name: Add emacs apt repository
    become: yes
    apt_repository:
      repo: ppa:ubuntu-elisp/ppa

  - name: Apt update and upgrade
    become: yes
    apt:
      upgrade: dist
      update_cache: yes

  - name: Installing multiple packages (emacs, curl, git)
    become: yes
    apt:
      pkg:
        - emacs-snapshot
        - curl
        - git
        - build-essential
        - linuxbrew-wrapper
      state: present

  - name: Ensure Linuxbrew is installed
    stat:
      path: "$HOME/.linuxbrew/bin/brew"
    register: "linuxbrew_check"

  - name: Fail if Linuxbrew is not installed and install_linuxbrew_if_missing is False
    fail:
      msg: "Linuxbrew is missing...Install it"
    when: >-
      not linuxbrew_check.stat.exists and
      not install_linuxbrew_if_missing

  - name: Installing Linuxbrew
    # shell: |
    #   /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
    #   echo 'eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)' >>~/.profile
    shell: |
      git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew
      mkdir ~/.linuxbrew/bin
      ln -s ~/.linuxbrew/Homebrew/bin/brew ~/.linuxbrew/bin
      echo 'eval $(~/.linuxbrew/bin/brew shellenv)' >>~/.profile
      eval $(~/.linuxbrew/bin/brew shellenv)
    when: >-
      not linuxbrew_check.stat.exists and
      install_linuxbrew_if_missing

  - name: Ensure Linuxbrew got installed
    stat:
      path: "$HOME/.linuxbrew/bin/brew"
    register: "linuxbrew_check_two"      

  - name: Updating Linuxbrew
    homebrew:
      update_homebrew: yes
    when: linuxbrew_check_two.stat.exists

  - name: Installing Linuxbrew packages
    homebrew:
      name: "{{ brew_packages }}"
      state: present
      upgrade_all: "{{ upgrade_homebrew_packages }}"
    when: linuxbrew_check_two.stat.exists

  - name: Installing Linuxbrew Cask packages
    homebrew:
      name: "{{ brew_cask_packages }}"
      state: present
      upgrade_all: "{{ upgrade_homebrew_packages }}"
    when: linuxbrew_check_two.stat.exists

  - name: Installing Snap packages
    become: yes
    snap:
      name: "{{ snap_packages }}"

  - name: Installing Snap classic confinment packages
    become: yes
    snap:
      classic: yes
      name: "{{ snap_classic_packages }}"
