---
- hosts: nanaya_vm
  remote_user: calizarr
  vars:
    apt_packages:
      - 'emacs-snapshot'
      - 'curl'
      - 'git'
      - 'build-essential'
      - 'linuxbrew-wrapper'
    brew_packages:
      - 'docker'
      - 'docker-compose'
      - 'git'
      - 'hub'
      - 'jq'
      - 'pyenv'
      - 'tmux'
      - 'zsh'
      - 'zsh-autosuggestions'
      - 'zsh-completions'
      - 'zsh-history-substring-search'
      - 'zsh-syntax-highlighting'
    snap_packages:
      - 'keepassxc'
    snap_classic_packages:
      - 'slack'
    ssh_items:
      # 0644, u=rw,g-rw,o-rw
      - { src: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa", dest: "{{ ansible_env.HOME }}/.ssh/id_rsa", mode: "u=rw,g-rw,o-rw" }
      - { src: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub", dest: "{{ ansible_env.HOME }}/.ssh/id_rsa.pub", mode: "u=rw,g=r,o=r" }
    install_linuxbrew_if_missing: true
    upgrade_homebrew_packages: false

  tasks:

  - name: Add emacs apt repository
    become: yes
    apt_repository:
      repo: ppa:ubuntu-elisp/ppa

  - name: Apt update and upgrade
    become: yes
    apt:
      upgrade: dist
      update_cache: yes

  - name: Installing multiple packages (emacs, curl, git)
    become: yes
    apt:
      pkg: "{{ apt_packages }}"
      state: present

  - name: Ensure Linuxbrew is installed
    stat:
      path: "$HOME/.linuxbrew/bin/brew"
    register: "linuxbrew_check"

  - name: Fail if Linuxbrew is not installed and install_linuxbrew_if_missing is False
    fail:
      msg: "Linuxbrew is missing...Install it"
    when: >-
      not linuxbrew_check.stat.exists and
      not install_linuxbrew_if_missing

  - name: Installing Linuxbrew
    shell: |
      git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew
      mkdir ~/.linuxbrew/bin
      ln -s ~/.linuxbrew/Homebrew/bin/brew ~/.linuxbrew/bin
      echo 'eval $(~/.linuxbrew/bin/brew shellenv)' >>~/.profile
      eval $(~/.linuxbrew/bin/brew shellenv)
    when: >-
      not linuxbrew_check.stat.exists and
      install_linuxbrew_if_missing

  - name: Ensure Linuxbrew got installed
    stat:
      path: "$HOME/.linuxbrew/bin/brew"
    register: "linuxbrew_check_two"      

  - name: Updating Linuxbrew
    homebrew:
      update_homebrew: yes
    when: linuxbrew_check_two.stat.exists

  - name: Installing Linuxbrew packages
    homebrew:
      name: "{{ brew_packages }}"
      state: present
      upgrade_all: "{{ upgrade_homebrew_packages }}"
    when: linuxbrew_check_two.stat.exists

  - name: Installing Snap packages
    become: yes
    snap:
      name: "{{ snap_packages }}"

  - name: Installing Snap classic confinement packages
    become: yes
    snap:
      classic: yes
      name: "{{ snap_classic_packages }}"

  - name: Set text scaling factor
    shell: "gsettings set org.gnome.desktop.interface text-scaling-factor 1.3"

  - name: Use WSL SSH key
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: "{{ item.mode }}"
    with_items: "{{ ssh_items }}"

  - name: Get emacs configuration
    git:
      repo: git@github.com:calizarr/.emacs.d.git
      dest: "{{ ansible_env.HOME }}/.emacs.d"

  - name: Get dotfiles etc. repo
    git:
      repo: git@github.com:calizarr/Misc.git
      dest: "{{ ansible_env.HOME }}/GitHub_Repos/Misc"
