---
ssh_items:
  # 0644, u=rw,g-rw,o-rw
  - { src: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa", dest: "{{ ansible_env.HOME }}/.ssh/id_rsa", mode: "u=rw,g-rw,o-rw" }
  - { src: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub", dest: "{{ ansible_env.HOME }}/.ssh/id_rsa.pub", mode: "u=rw,g=r,o=r" }

git_config:
  user:
    - { name: "user.email", value: "{{ git_email | default('None') }}" }
    - { name: "user.name", value: "{{ git_user | default('None') }}" }
    - { name: "oh-my-zsh.hide-dirty", value: "1" }
