---
- hosts: "{{ host | default('nanaya_vm') }}"
  remote_user: "{{ remote_usr | default('calizarr') }}"

  vars:
    bash_rc: "{{ ansible_env.HOME }}/.bashrc"
    nix_bins: "{{ ansible_env.HOME }}/.nix-profile/bin"

  environment:
    PATH: "{{ ansible_env.HOME }}/.nix-profile/bin:{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.HOME }}/.pyenv/bin:{{ ansible_env.HOME }}/.krew/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
    NIX_PROFILES: "/nix/var/nix/profiles/default {{ ansible_env.HOME }}/.nix-profile"
    NIX_PATH: "{{ ansible_env.HOME }}/.nix-defexpr/channels"
    NIX_SSL_CERT_FILE: "/etc/ssl/certs/ca-certificates.crt"

  tasks:
  - name: Create .local/bin
    ansible.builtin.file:
      path: "{{ ansible_env.HOME }}/.local/bin"
      state: directory
      mode: u=rwx,g=rwx,o=rx

  - name: Installing packages
    include_role:
      name: './roles/packages'

  - name: Installing Nix
    include_role:
      name: './roles/nix'

  - name: Configure pyenv
    include_role:
      name: './roles/pyenvs'

  - name: Install Sdkman
    include_role:
      name: './roles/sdkman'

  - name: GCCEMACS
    include_role:
      name: './roles/gccemacs'

  - name: Configure ssh, emacs, tmux, git
    include_role:
      name: './roles/configuration'

  - name: Install zsh, oh-my-zsh, and configure
    include_role:
      name: './roles/zsh'

  - name: Reboot Ubuntu VM post package installation
    become: yes
    reboot:
      connect_timeout: 20
      msg: "Reboot initiated post package installation"
      pre_reboot_delay: 6
      post_reboot_delay: 30
      reboot_timeout: 600

  - name: Change gnome via gsettings etc.
    include_role:
      name: './roles/gnome_settings'

  - name: Configure Terminator
    include_role:
      name: './roles/terminator'

  - name: Chrome Installation and Configuration
    include_role:
      name: './roles/chrome'

  - name: Add Kubernetes Plugins And Binaries
    include_role:
      name: './roles/kubernetes'

  - name: Reboot Ubuntu VM after ansible playbook has finished
    become: yes
    reboot:
      connect_timeout: 20
      msg: "Final reboot initiated before machine is operational"
      pre_reboot_delay: 6
      post_reboot_delay: 30
      reboot_timeout: 600
