---
- name: Create Terminator plugins directory if it does not exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/terminator/plugins"
    state: directory
    mode: '0755'

- name: Install Terminator themes via wget
  ansible.builtin.get_url:
    url: https://git.io/v5Zww
    dest: "{{ ansible_env.HOME }}/.config/terminator/plugins/terminator-themes.py"
    mode: '0755'

- name: Copy Terminator Config to Proper Directory
  ansible.builtin.copy:
    content: |
      [global_config]
        borderless = True
        enabled_plugins = TerminatorThemes, LaunchpadCodeURLHandler, APTURLHandler, LaunchpadBugURLHandler
      [keybindings]
        hide_window = <Shift><Alt>at
        next_tab = <Primary>Tab
        prev_tab = <Primary><Shift>Tab
      [layouts]
        [[default]]
          [[[child1]]]
            parent = window0
            profile = default
            type = Terminal
          [[[window0]]]
            parent = ""
            type = Window
      [plugins]
      [profiles]
        [[default]]
          background_darkness = 0.7
          # background_type = transparent
          background_type = "solid"
          cursor_color = "#aaaaaa"
          font = DejaVu Sans Mono 11
          palette = "#000000:#cc0000:#4e9a06:#c4a000:#3465a4:#75507b:#06989a:#d3d7cf:#555753:#ef2929:#8ae234:#fce94f:#729fcf:#ad7fa8:#34e2e2:#eeeeec"
          show_titlebar = False
          use_system_font = False
    dest: "{{ ansible_env.HOME}}/.config/terminator/config"

- name: Set Terminator Tab CSS
  ansible.builtin.copy:
    dest: "{{ ansible_env.HOME }}/.config/gtk-3.0/gtk.css"
    content: |
      .terminator-terminal-window notebook tab {
          background-color: #222;
          padding: 0.2em;
          border: 0;
          border-color: #444;
          border-style: solid;
          border-width: 1px;
      }

      .terminator-terminal-window notebook tab:checked {
          background-color: #000;
          background-image: none;
      }

      .terminator-terminal-window notebook tab label {
          color: #ddd;
      }

      .terminator-terminal-window notebook tab:checked label {
          color: #76C802;
          font-weight: 500;
      }

      .terminator-terminal-window notebook tab button {
          padding: 0;
          background-color: transparent;
          color: #ccc;
      }

      .terminator-terminal-window notebook header {
          background-color: #444;
      }

      .terminator-terminal-window notebook tab button:hover {
          border: 0;
          background-image: none;
          border-color: #444;
          border-style: solid;
          border-width: 1px;
      }
